services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4567:4567"
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - CLEAR_TMP_FOLDER=0

      # Executor type: 'docker' simulates Lambda environment better
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=30
      - LAMBDA_DOCKER_NETWORK=nginx-proxy
      - DOCKER_HOST=unix:///var/run/docker.sock
      
      # Services enabled
      - SERVICES=lambda,sqs,logs,cloudformation,iam,cloudwatch,apigateway,events,sts,ec2,s3,dynamodb

    volumes:
      - "./localstack-data:/tmp/localstack/data"
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
