# Configuración del Backend para PROD (AWS Real)
bucket         = "tu-bucket-prod-terraform-state"
key            = "gofibercore/terraform.tfstate"
region         = "us-east-1"
dynamodb_table = "terraform-lock"
encrypt        = true
# No se usan endpoints locales
