# Configuración del Backend para LocalStack
bucket                      = "terraform-state"
key                         = "gofibercore/terraform.tfstate"
region                      = "us-east-1"
dynamodb_table              = "terraform-lock"
encrypt                     = true
endpoint                    = "http://127.0.0.1:4566"
dynamodb_endpoint           = "http://127.0.0.1:4566"
iam_endpoint                = "http://127.0.0.1:4566"
sts_endpoint                = "http://127.0.0.1:4566"
skip_credentials_validation = true
skip_metadata_api_check     = true
skip_region_validation      = true
force_path_style            = true
