{{- if .Values.cronjob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "gofiber-app.fullname" . }}
  labels:
    {{- include "gofiber-app.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "gofiber-app.selectorLabels" . | nindent 12 }}
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                {{- range $key, $val := .Values.env }}
                - name: {{ $key }}
                  value: {{ $val | quote }}
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          restartPolicy: OnFailure
{{- end }}
