# Default values for gofiber-app.

nameOverride: ""
fullnameOverride: ""

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

service:
  enabled: false
  type: ClusterIP
  port: 80
  targetPort: 3000

# Probes (Liveness/Readiness)
probes:
  enabled: false
  liveness:
    path: "/api/v1/health"
    port: 3000
    initialDelaySeconds: 15
    periodSeconds: 20
  readiness:
    path: "/api/v1/health"
    port: 3000
    initialDelaySeconds: 5
    periodSeconds: 10

env: {}
#  KEY: "value"

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# KEDA Autoscaling
autoscaling:
  enabled: false
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers: []
    # - type: aws-sqs-queue
    #   metadata:
    #     queueURL: ""
    #     queueLength: "5"
    #     awsRegion: "us-east-1"
    #     identityOwner: operator

cronjob:
  enabled: false
  schedule: "*/1 * * * *"
