# 1. Empezamos con la imagen oficial de Go en la versión exacta que usa el proyecto.
FROM golang:1.25-alpine

WORKDIR /app

ENV GOTOOLCHAIN=local

RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

COPY . .

ENTRYPOINT ["/go/bin/golangci-lint"]

CMD ["run"]
