FROM golang:1.24.4

WORKDIR /app

RUN go install github.com/air-verse/air@latest

ARG FOLDER
ENV FOLDER=$FOLDER

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air", "-c", ".air-dev.toml"]

