// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire gen -tags "wireinject"
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/sqs"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/joho/godotenv"
	"github.com/redis/go-redis/v9"
	"go-fiber-core/internal/database/connections/gorm"
	"go-fiber-core/internal/database/connections/pgx"
	redis2 "go-fiber-core/internal/database/connections/redis"
	"go-fiber-core/internal/dtos/config"
	"go-fiber-core/internal/dtos/connect"
	"go-fiber-core/internal/handlers"
	"go-fiber-core/internal/models"
	"go-fiber-core/internal/repositories/authenticationlog"
	"go-fiber-core/internal/repositories/bank"
	"go-fiber-core/internal/repositories/bulkjob"
	"go-fiber-core/internal/repositories/bulkjobconfig"
	"go-fiber-core/internal/repositories/bulkjobitem"
	"go-fiber-core/internal/repositories/catalog"
	"go-fiber-core/internal/repositories/menu"
	"go-fiber-core/internal/repositories/menu_user"
	"go-fiber-core/internal/repositories/refreshtoken"
	"go-fiber-core/internal/repositories/rol"
	"go-fiber-core/internal/repositories/session"
	"go-fiber-core/internal/repositories/user"
	"go-fiber-core/internal/server"
	"go-fiber-core/internal/services"
	"go-fiber-core/internal/services/auth"
	"go-fiber-core/internal/services/authlog"
	bank2 "go-fiber-core/internal/services/bank"
	catalog2 "go-fiber-core/internal/services/catalog"
	"go-fiber-core/internal/services/imports"
	menu2 "go-fiber-core/internal/services/menu"
	menu_user2 "go-fiber-core/internal/services/menu_user"
	"go-fiber-core/internal/services/pagination"
	"go-fiber-core/internal/services/processlifecycle"
	"go-fiber-core/internal/services/queue"
	rol2 "go-fiber-core/internal/services/rol"
	user2 "go-fiber-core/internal/services/user"
	"log"
	"os"
)

// Injectors from wire.go:

// InitializeServer para API (Local/Docker)
func InitializeServer(configPath string) (*server.FiberServer, func(), error) {
	appConfig, err := provideAppConfigServer(configPath)
	if err != nil {
		return nil, nil, err
	}
	gormConnectService, cleanup, err := provideGormService(appConfig)
	if err != nil {
		return nil, nil, err
	}
	pgxWritePool, cleanup2, err := providePgxWritePool(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	pgxReadPool, cleanup3, err := providePgxReadPool(appConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	client, cleanup4, err := provideRedisClient(appConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	connectDTO := provideConnectDTO(gormConnectService, pgxWritePool, pgxReadPool, client)
	userReader := user.NewUserReaderRepo()
	userWriter := user.NewUserWriterRepo()
	refreshTokenReader := refreshtoken.NewRefreshTokenReaderRepo()
	refreshTokenWriter := refreshtoken.NewRefreshTokenWriterRepo()
	refreshTokenRepository := refreshtoken.NewRefreshTokenRepository(refreshTokenReader, refreshTokenWriter)
	sessionReader := session.NewSessionReaderRepo()
	sessionWriter := session.NewSessionWriterRepo()
	service := provideSessionPaginationService()
	sessionPagination := session.NewSessionPaginationRepo(service)
	sessionRepository := session.NewSessionRepository(sessionReader, sessionWriter, sessionPagination)
	tokenService := provideTokenService(appConfig)
	menuReader := menu.NewMenuReaderRepository(connectDTO)
	menuReaderService := menu2.NewMenuReaderService(menuReader)
	authenticationLogWriter := authenticationlog.NewAuthenticationLogWriterRepo()
	authLogService := authlog.NewAuthLogService(connectDTO, authenticationLogWriter)
	authService := auth.NewAuthService(userReader, userWriter, refreshTokenRepository, sessionRepository, tokenService, menuReaderService, authLogService, connectDTO)
	authHandler := handlers.NewAuthHandler(authService)
	userWriterService := user2.NewUserWriterService(connectDTO, userWriter, userReader)
	paginationService := provideUserPaginationService()
	userPaginator := user.NewUserPaginatorRepo(paginationService)
	userReaderService := user2.NewUserReaderService(connectDTO, userReader, userPaginator)
	userHandler := handlers.NewUserHandler(userWriterService, userReaderService)
	catalogRepository := catalog.NewCatalogRepository(client)
	bankWriter := bank.NewBankWriterRepo(catalogRepository)
	bankReader := bank.NewBankReaderRepo()
	bankWriterService := bank2.NewBankWriterService(connectDTO, bankWriter, bankReader)
	bankReaderService := bank2.NewBankReaderService(connectDTO, bankReader)
	service2 := provideBankPaginationService()
	bankPagination := bank.NewBankPaginationRepo(service2)
	bankPaginationService := bank2.NewBankPaginationService(connectDTO, bankPagination)
	bankHandler := handlers.NewBankHandler(bankWriterService, bankReaderService, bankPaginationService)
	catalogService := catalog2.NewCatalogService(catalogRepository, connectDTO)
	catalogHandler := handlers.NewCatalogHandler(catalogService)
	rolWriter := rol.NewRolWriterRepo()
	rolReader := rol.NewRolReaderRepo()
	rolWriterService := rol2.NewRolWriterService(connectDTO, rolWriter, rolReader)
	rolReaderService := rol2.NewRolReaderService(connectDTO, rolReader)
	service3 := provideRolPaginationService()
	rolPagination := rol.NewRolPaginationRepo(service3)
	rolPaginationService := rol2.NewRolPaginationService(connectDTO, rolPagination)
	rolHandler := handlers.NewRolHandler(rolWriterService, rolReaderService, rolPaginationService)
	menuWriter := menu.NewMenuWriterRepository(connectDTO)
	menuWriterService := menu2.NewMenuWriterService(menuWriter, connectDTO)
	menuHandler := handlers.NewMenuHandler(menuWriterService, menuReaderService)
	service4 := provideMenuUserPaginationService()
	menuUserPagination := menu_user.NewMenuUserPaginationRepository(service4)
	menuUserPaginationService := menu_user2.NewMenuUserPaginationService(connectDTO, menuUserPagination)
	menuUserHandler := handlers.NewMenuUserHandler(menuUserPaginationService)
	databaseService := services.NewDatabaseService(appConfig, connectDTO)
	databaseHandler := handlers.NewDatabaseHandler(databaseService)
	processlifecycleService := processlifecycle.NewService(connectDTO)
	processLifecycleHandler := handlers.NewProcessLifecycleHandler(processlifecycleService)
	bulkJobReader := bulkjob.NewBulkJobReaderRepo()
	bulkJobWriter := bulkjob.NewBulkJobWriterRepo()
	bulkJobItemReader := bulkjobitem.NewBulkJobItemReaderRepo()
	bulkJobItemWriter := bulkjobitem.NewBulkJobItemWriterRepo()
	bulkJobConfigReader := bulkjobconfig.NewBulkJobConfigReaderRepo()
	importsService := imports.NewService(connectDTO, bulkJobReader, bulkJobWriter, bulkJobItemReader, bulkJobItemWriter, bulkJobConfigReader)
	importHandler := handlers.NewImportHandler(importsService)
	awsConfigProvider, err := provideAWSService()
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	messageQueue := provideSQSService(awsConfigProvider)
	fiberServer, cleanup5, err := server.NewFiberServer(appConfig, connectDTO, authHandler, userHandler, bankHandler, catalogHandler, rolHandler, menuHandler, menuUserHandler, databaseHandler, processLifecycleHandler, importHandler, tokenService, userWriterService, messageQueue)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return fiberServer, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// InitializeAppContainer para Crons, Lambdas y CLI (Lógica pura)
func InitializeAppContainer(configPath string) (*AppContainer, func(), error) {
	appConfig, err := provideAppConfigAWS(configPath)
	if err != nil {
		return nil, nil, err
	}
	gormConnectService, cleanup, err := provideGormService(appConfig)
	if err != nil {
		return nil, nil, err
	}
	pgxWritePool, cleanup2, err := providePgxWritePool(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	pgxReadPool, cleanup3, err := providePgxReadPool(appConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	client, cleanup4, err := provideRedisClient(appConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	connectDTO := provideConnectDTO(gormConnectService, pgxWritePool, pgxReadPool, client)
	userWriter := user.NewUserWriterRepo()
	userReader := user.NewUserReaderRepo()
	userWriterService := user2.NewUserWriterService(connectDTO, userWriter, userReader)
	service := provideUserPaginationService()
	userPaginator := user.NewUserPaginatorRepo(service)
	userReaderService := user2.NewUserReaderService(connectDTO, userReader, userPaginator)
	catalogRepository := catalog.NewCatalogRepository(client)
	bankWriter := bank.NewBankWriterRepo(catalogRepository)
	bankReader := bank.NewBankReaderRepo()
	bankWriterService := bank2.NewBankWriterService(connectDTO, bankWriter, bankReader)
	bankReaderService := bank2.NewBankReaderService(connectDTO, bankReader)
	refreshTokenReader := refreshtoken.NewRefreshTokenReaderRepo()
	refreshTokenWriter := refreshtoken.NewRefreshTokenWriterRepo()
	refreshTokenRepository := refreshtoken.NewRefreshTokenRepository(refreshTokenReader, refreshTokenWriter)
	sessionReader := session.NewSessionReaderRepo()
	sessionWriter := session.NewSessionWriterRepo()
	paginationService := provideSessionPaginationService()
	sessionPagination := session.NewSessionPaginationRepo(paginationService)
	sessionRepository := session.NewSessionRepository(sessionReader, sessionWriter, sessionPagination)
	tokenService := provideTokenService(appConfig)
	menuReader := menu.NewMenuReaderRepository(connectDTO)
	menuReaderService := menu2.NewMenuReaderService(menuReader)
	authenticationLogWriter := authenticationlog.NewAuthenticationLogWriterRepo()
	authLogService := authlog.NewAuthLogService(connectDTO, authenticationLogWriter)
	authService := auth.NewAuthService(userReader, userWriter, refreshTokenRepository, sessionRepository, tokenService, menuReaderService, authLogService, connectDTO)
	databaseService := services.NewDatabaseService(appConfig, connectDTO)
	awsConfigProvider, err := provideAWSService()
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	messageQueue := provideSQSService(awsConfigProvider)
	processlifecycleService := processlifecycle.NewService(connectDTO)
	appContainer := &AppContainer{
		Config:                  appConfig,
		Connect:                 connectDTO,
		UserWriterService:       userWriterService,
		UserReaderService:       userReaderService,
		BankWriterService:       bankWriterService,
		BankReaderService:       bankReaderService,
		AuthService:             authService,
		DatabaseService:         databaseService,
		QueueService:            messageQueue,
		ProcessLifecycleService: processlifecycleService,
	}
	return appContainer, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// InitializeAWS (Mantenido por compatibilidad simple)
func InitializeAWS(configPath string) (*AWSConfigResponse, func(), error) {
	appConfig, err := provideAppConfigAWS(configPath)
	if err != nil {
		return nil, nil, err
	}
	gormConnectService, cleanup, err := provideGormService(appConfig)
	if err != nil {
		return nil, nil, err
	}
	pgxWritePool, cleanup2, err := providePgxWritePool(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	pgxReadPool, cleanup3, err := providePgxReadPool(appConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	client, cleanup4, err := provideRedisClient(appConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	connectDTO := provideConnectDTO(gormConnectService, pgxWritePool, pgxReadPool, client)
	awsConfigResponse := &AWSConfigResponse{
		Config:  appConfig,
		Connect: connectDTO,
	}
	return awsConfigResponse, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type PgxWritePool *pgxpool.Pool

type PgxReadPool *pgxpool.Pool

// AppContainer contiene la lógica de negocio completa sin el servidor HTTP
type AppContainer struct {
	Config                  *config.AppConfig
	Connect                 *connect.ConnectDTO
	UserWriterService       user2.UserWriterService
	UserReaderService       user2.UserReaderService
	BankWriterService       bank2.BankWriterService
	BankReaderService       bank2.BankReaderService
	AuthService             auth.AuthService
	DatabaseService         services.DatabaseService
	QueueService            queue.MessageQueue
	ProcessLifecycleService processlifecycle.Service
}

// AWSConfigResponse se mantiene para compatibilidad si lo usas en otros lados
type AWSConfigResponse struct {
	Config  *config.AppConfig
	Connect *connect.ConnectDTO
}

func provideAppConfigServer(configPath string) (*config.AppConfig, error) {
	_ = godotenv.Load()
	return config.NewAppConfig(configPath)
}

func provideAppConfigAWS(configPath string) (*config.AppConfig, error) {
	_ = godotenv.Load()
	validateLambdaEnv()
	return config.NewAppConfig(configPath)
}

func validateLambdaEnv() {
	required := []string{"JWT_ACCESS_SECRET", "JWT_REFRESH_SECRET"}
	for _, v := range required {
		if os.Getenv(v) == "" {
			log.Fatalf("❌ Variable de entorno requerida no definida: %s", v)
		}
	}
}

func provideGormService(cfg *config.AppConfig) (*gorm.GormConnectService, func(), error) {
	return gorm.NewGormConnectService(cfg.MultiDatabaseConfig)
}

func provideRedisClient(cfg *config.AppConfig) (*redis.Client, func(), error) {
	return redis2.NewRedisClient(cfg.Redis)
}

func providePgxWritePool(cfg *config.AppConfig) (PgxWritePool, func(), error) {
	pool, cleanup, err := pgx.NewPgxConnection(cfg.MultiDatabaseConfig.Pgx.Write)
	return PgxWritePool(pool), cleanup, err
}

func providePgxReadPool(cfg *config.AppConfig) (PgxReadPool, func(), error) {
	pool, cleanup, err := pgx.NewPgxConnection(cfg.MultiDatabaseConfig.Pgx.Read)
	return PgxReadPool(pool), cleanup, err
}

func provideConnectDTO(gormService *gorm.GormConnectService, w PgxWritePool, r PgxReadPool, rd *redis.Client) *connect.ConnectDTO {
	return &connect.ConnectDTO{
		ConnectGormWrite: gormService.GetWriteDB(),
		ConnectGormRead:  gormService.GetReadDB(),
		ConnectPgxWrite:  (*pgxpool.Pool)(w),
		ConnectPgxRead:   (*pgxpool.Pool)(r),
		ConnectRedis:     rd,
	}
}

func provideTokenService(cfg *config.AppConfig) auth.TokenService {
	return auth.NewTokenService(cfg)
}

func provideUserPaginationService() pagination.Service[models.User] {
	return pagination.NewPaginationService[models.User]()
}

func provideRolPaginationService() pagination.Service[models.Role] {
	return pagination.NewPaginationService[models.Role]()
}

func provideBankPaginationService() pagination.Service[models.Bank] {
	return pagination.NewPaginationService[models.Bank]()
}

func provideMenuUserPaginationService() pagination.Service[models.MenuUser] {
	return pagination.NewPaginationService[models.MenuUser]()
}

func provideSessionPaginationService() pagination.Service[models.Session] {
	return pagination.NewPaginationService[models.Session]()
}

func provideAWSService() (queue.AWSConfigProvider, error) {
	return queue.NewAWSService(context.Background())
}

func provideSQSService(awsService queue.AWSConfigProvider) queue.MessageQueue {
	cfg := awsService.GetConfig()
	client := sqs.NewFromConfig(cfg)
	url := os.Getenv("SQS_QUEUE_URL")
	return queue.NewSQSService(client, url)
}

var connectionSet = wire.NewSet(
	provideGormService,
	provideRedisClient,
	providePgxWritePool,
	providePgxReadPool,
	provideConnectDTO,
)

var repositorySet = wire.NewSet(user.NewUserReaderRepo, user.NewUserWriterRepo, user.NewUserPaginatorRepo, user.NewUserRepository, bank.NewBankReaderRepo, bank.NewBankWriterRepo, bank.NewBankCrudRepository, bank.NewBankPaginationRepo, refreshtoken.NewRefreshTokenReaderRepo, refreshtoken.NewRefreshTokenWriterRepo, refreshtoken.NewRefreshTokenRepository, session.NewSessionReaderRepo, session.NewSessionWriterRepo, session.NewSessionPaginationRepo, session.NewSessionRepository, menu.NewMenuReaderRepository, menu.NewMenuWriterRepository, menu_user.NewMenuUserPaginationRepository, rol.NewRolReaderRepo, rol.NewRolWriterRepo, rol.NewRolCrudRepository, rol.NewRolPaginationRepo, catalog.NewCatalogRepository, authenticationlog.NewAuthenticationLogWriterRepo, authenticationlog.NewAuthenticationLogRepository, bulkjob.NewBulkJobReaderRepo, bulkjob.NewBulkJobWriterRepo, bulkjobitem.NewBulkJobItemReaderRepo, bulkjobitem.NewBulkJobItemWriterRepo, bulkjobconfig.NewBulkJobConfigReaderRepo, bulkjobconfig.NewBulkJobConfigWriterRepo)

var serviceSet = wire.NewSet(
	provideTokenService, authlog.NewAuthLogService, auth.NewAuthService, imports.NewService, provideAWSService,
	provideSQSService,

	provideUserPaginationService,
	provideBankPaginationService,
	provideMenuUserPaginationService,
	provideRolPaginationService,
	provideSessionPaginationService, services.NewTransactionManager, services.NewDatabaseService, user2.NewUserReaderService, user2.NewUserWriterService, bank2.NewBankReaderService, bank2.NewBankWriterService, bank2.NewBankPaginationService, bank2.NewDeactivationService, menu2.NewMenuReaderService, menu2.NewMenuWriterService, rol2.NewRolReaderService, rol2.NewRolWriterService, rol2.NewRolPaginationService, menu_user2.NewMenuUserPaginationService, catalog2.NewCatalogService, processlifecycle.NewService,
)

var handlerSet = wire.NewSet(handlers.NewAuthHandler, handlers.NewUserHandler, handlers.NewBankHandler, handlers.NewDatabaseHandler, handlers.NewMenuHandler, handlers.NewMenuUserHandler, handlers.NewRolHandler, handlers.NewCatalogHandler, handlers.NewProcessLifecycleHandler, handlers.NewImportHandler)
