AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  SqsQueueUrl:
    Type: String
  SqsQueueName:
    Type: String
  SqsQueueArn:
    Type: String

Resources:
  GoFiberCoreApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GoFiberCoreApi
      CodeUri: ../sam-compile/api/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          # Construir URL de LocalStack directamente
          SQS_QUEUE_URL: !Sub "http://localhost:4566/000000000000/${SqsQueueName}"
          SQS_QUEUE_NAME: !Ref SqsQueueName
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !Ref SqsQueueArn
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY

        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "URL de la API Gateway"
    Value: !Sub "http://localhost:4566/restapis/${ServerlessRestApi}/Prod/_user_request_"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"

  ApiGatewayId:
    Description: "ID del API Gateway"
    Value: !Ref ServerlessRestApi
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayId"
