AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Cron de GoFiberCoreEvery1minCron en every-1min-cron

Resources:
  GoFiberCoreEvery1minCron:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GoFiberCoreEvery1minCron
      CodeUri: ../sam-compile/every-1min-cron/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Timeout: 30
      MemorySize: 128
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: "rate(1 minute)"
      Tags:
        ForceUpdate: "2025-08-09-01"