INSERT INTO banks ("name", entity_code, enabled) VALUES
('Banco de la Nación Argentina', '011', true),
('Banco Santander', '072', true),
('Banco Galicia', '007', true),
('BBVA Argentina', '017', true),
('Banco Macro', '285', true),
('HSBC Bank Argentina', '150', true),
('ICBC Argentina', '015', true),
('Banco Credicoop Cooperativo Limitado', '191', true),
('Banco Patagonia', '034', true),
('Banco de la Ciudad de Buenos Aires', '029', true),
('Banco de la Provincia de Buenos Aires', '014', true),
('Banco Hipotecario', '044', true),
('Banco de Corrientes', '094', true),
('Banco de la Provincia de Córdoba', '020', true),
('Banco del Chubut', '093', true),
('Banco de La Pampa', '097', true),
('Banco de San Juan', '045', true),
('Banco de Santa Cruz', '086', true),
('Banco del Sol', '454', true),
('Banco del Tucumán', '431', true),
('Banco Municipal de Rosario', '065', true),
('Banco Provincia del Neuquén', '092', true),
('Banco Rioja', '432', true),
('Brubank', '426', true),
('Wilobank', '428', false),
('Reba', '444', true),
('Ualá', '405', true),
('Naranja X', '403', true),
('Citibank Argentina', '016', true),
('Banco Comafi', '299', true),
('Banco Supervielle', '027', true),
('Banco Itaú Argentina', '259', true),
('Banco CMF', '321', true),
('Banco Mariva', '322', false),
('Banco BICA', '384', true);
