apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-consumer
  namespace: default
  labels:
    app: sqs-consumer
spec:
  replicas: 1 # KEDA ajustará esto dinámicamente
  selector:
    matchLabels:
      app: sqs-consumer
  template:
    metadata:
      labels:
        app: sqs-consumer
    spec:
      containers:
        - name: sqs-consumer
          image: sqs-consumer
          imagePullPolicy: IfNotPresent # IMPORTANTE: Usa la imagen local de OrbStack
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: APP_ENV
              value: "local"
            - name: AWS_REGION
              value: "us-east-1"
            # Configuración para conectar con LocalStack desde dentro del pod
            - name: AWS_ENDPOINT_URL
              value: "http://host.docker.internal:4566"
            - name: SQS_QUEUE_URL
              # Asegúrate de que esta URL coincida con tu cola en LocalStack
              value: "http://host.docker.internal:4566/000000000000/gofibercorequeue"
            - name: JWT_ACCESS_SECRET
              value: "test-secret"
            - name: JWT_REFRESH_SECRET
              value: "test-secret"
            - name: JWT_ACCESS_TTL_MINUTES
              value: "15m"
            - name: JWT_REFRESH_TTL_DAYS
              value: "720h"
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "test"

            # GORM Writer
            - name: GORM_WRITE_DRIVER
              value: "postgres"
            - name: GORM_WRITE_HOST
              value: "host.docker.internal"
            - name: GORM_WRITE_PORT
              value: "5432"
            - name: GORM_WRITE_USER
              value: "postgres"
            - name: GORM_WRITE_PASSWORD
              value: "postgres"
            - name: GORM_WRITE_DBNAME
              value: "go_fiber_core"
            - name: GORM_WRITE_SCHEMA
              value: "public"
            - name: GORM_WRITE_MAX_OPEN_CONNS
              value: "15"
            - name: GORM_WRITE_MAX_IDLE_CONNS
              value: "10"
            - name: GORM_WRITE_CONN_MAX_LIFETIME_SECONDS
              value: "300"

            # GORM Reader
            - name: GORM_READ_DRIVER
              value: "postgres"
            - name: GORM_READ_HOST
              value: "host.docker.internal"
            - name: GORM_READ_PORT
              value: "5432"
            - name: GORM_READ_USER
              value: "postgres"
            - name: GORM_READ_PASSWORD
              value: "postgres"
            - name: GORM_READ_DBNAME
              value: "go_fiber_core"

            # PGX Writer
            - name: PGX_WRITE_HOST
              value: "host.docker.internal"
            - name: PGX_WRITE_PORT
              value: "5432"
            - name: PGX_WRITE_USER
              value: "postgres"
            - name: PGX_WRITE_PASSWORD
              value: "postgres"
            - name: PGX_WRITE_DBNAME
              value: "go_fiber_core"
            - name: PGX_WRITE_MAX_CONNS
              value: "15"

            # PGX Reader
            - name: PGX_READ_HOST
              value: "host.docker.internal"
            - name: PGX_READ_PORT
              value: "5432"
            - name: PGX_READ_USER
              value: "postgres"
            - name: PGX_READ_PASSWORD
              value: "postgres"
            - name: PGX_READ_DBNAME
              value: "go_fiber_core"
            - name: PGX_READ_MAX_CONNS
              value: "15"

            # JWT
            - name: JWT_ACCESS_TTL_MINUTES
              value: "15m"
            - name: JWT_REFRESH_TTL_DAYS
              value: "720h"
            - name: JWT_ACCESS_SECRET
              value: "test-secret"
            - name: JWT_REFRESH_SECRET
              value: "test-secret"
            - name: GORM_READ_SCHEMA
              value: "public"
            - name: GORM_READ_MAX_OPEN_CONNS
              value: "15"
            - name: GORM_READ_MAX_IDLE_CONNS
              value: "10"
            - name: GORM_READ_CONN_MAX_LIFETIME_SECONDS
              value: "300"

            # PGX Writer
            - name: PGX_WRITE_HOST
              value: "host.docker.internal"
            - name: PGX_WRITE_PORT
              value: "5432"
            - name: PGX_WRITE_USER
              value: "postgres"
            - name: PGX_WRITE_PASSWORD
              value: "postgres"
            - name: PGX_WRITE_DBNAME
              value: "go_fiber_core"
            - name: PGX_WRITE_MAX_CONNS
              value: "15"

            # PGX Reader
            - name: PGX_READ_HOST
              value: "host.docker.internal"
            - name: PGX_READ_PORT
              value: "5432"
            - name: PGX_READ_USER
              value: "postgres"
            - name: PGX_READ_PASSWORD
              value: "postgres"
            - name: PGX_READ_DBNAME
              value: "go_fiber_core"
            - name: PGX_READ_MAX_CONNS
              value: "15"

            # Redis
            - name: REDIS_HOST
              value: "host.docker.internal"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
            - name: REDIS_DATABASE
              value: "0"
            - name: REDIS_EXPIRES_IN_SECONDS
              value: "230"
            - name: POOL_SIZE
              value: "50"
